/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package anglada.sensebrutor;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Andreu
 */
public class DownloadPanel extends javax.swing.JPanel {

    /**
     * Creates new form DownloadPanel
     */
    private SenseBrutor mainFrame;
    private String downloadedFilePath;
    public DownloadPanel(SenseBrutor mainFrame) {
        this.mainFrame = mainFrame;

        initComponents();
        jButtonPlay.setVisible(false);
        jButtonDownload.setEnabled(false);
        jProgressBarDownload.setVisible(false);
        jLabelLoadFormat.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTittle = new javax.swing.JLabel();
        jLabelURL = new javax.swing.JLabel();
        jTextFieldURL = new javax.swing.JTextField();
        jLabelFormat = new javax.swing.JLabel();
        jComboBoxFormat = new javax.swing.JComboBox<>();
        jButtonDownload = new javax.swing.JButton();
        jProgressBarDownload = new javax.swing.JProgressBar();
        jLabelProgress = new javax.swing.JLabel();
        jButtonPlay = new javax.swing.JButton();
        jLabelLoadFormat = new javax.swing.JLabel();

        setLayout(null);

        jLabelTittle.setText("SenseBrutor");
        add(jLabelTittle);
        jLabelTittle.setBounds(250, 20, 70, 16);

        jLabelURL.setText("URL:");
        add(jLabelURL);
        jLabelURL.setBounds(70, 50, 30, 16);

        jTextFieldURL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldURLFocusLost(evt);
            }
        });
        add(jTextFieldURL);
        jTextFieldURL.setBounds(120, 48, 340, 30);

        jLabelFormat.setText("Formato:");
        add(jLabelFormat);
        jLabelFormat.setBounds(60, 90, 60, 16);

        jComboBoxFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFormatActionPerformed(evt);
            }
        });
        add(jComboBoxFormat);
        jComboBoxFormat.setBounds(120, 90, 170, 30);

        jButtonDownload.setText("Descargar");
        jButtonDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownloadActionPerformed(evt);
            }
        });
        add(jButtonDownload);
        jButtonDownload.setBounds(210, 130, 150, 23);
        add(jProgressBarDownload);
        jProgressBarDownload.setBounds(130, 180, 300, 30);
        add(jLabelProgress);
        jLabelProgress.setBounds(260, 160, 100, 16);

        jButtonPlay.setText("Reproducir");
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });
        add(jButtonPlay);
        jButtonPlay.setBounds(220, 240, 120, 23);

        jLabelLoadFormat.setText("Cargando formatos...");
        add(jLabelLoadFormat);
        jLabelLoadFormat.setBounds(200, 160, 140, 16);
    }// </editor-fold>//GEN-END:initComponents
    
    // Método simple per extreure el porcentge de descarrega la línea de yt-dlp per despres posar dins el progress bar
    private Integer parsePercentage(String line) {
        try {
            line = line.trim();
            if (line.startsWith("[download]") && line.contains("%")) {
                // Ejemplo de línea: "[download]  40.0% of  322.51MiB at  500.39KiB/s ETA 10:59"
                int idx = line.indexOf("%");
                String perc = line.substring(0, idx).replace("[download]", "").trim(); // "40.0"
                float f = Float.parseFloat(perc); // 40.0
                return Math.round(f); // redondear a entero
            }
        } catch (Exception e) {
            // ignorar errores de parse
        }
        return null;
    }
    
    /*Accio del boto descarregar, inclou progresbar i quan troba " " una vegada a finalitzat asigna la variable downloadedFilePath.
    downloadedFilePath serveix per una vegada descarregat obrir l'arxiu al reproductor predeterminat*/
    private void jButtonDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownloadActionPerformed
        jProgressBarDownload.setVisible(true);
        PreferencesPanel prefs = mainFrame.getPreferencesPanel();

        String downloadPath = prefs.getDownloadPath();
        String ytdlpPath = prefs.getYTDLPPath();
        String selectedItem = (String) jComboBoxFormat.getSelectedItem();
        final String formatCode;
        if (selectedItem != null) {
            formatCode = selectedItem.split("\\s+")[0];
        } else {
            formatCode = "best";
        }
        int maxVelocity = prefs.getMaxVelocity();

        String url = jTextFieldURL.getText().trim();
        if (url.isEmpty()) {
            System.out.println("URL vacía");
            return;
        }

        jProgressBarDownload.setValue(0);
        jLabelProgress.setText("0%");

        SwingWorker<Void, Integer> worker = new SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                ProcessBuilder pb = new ProcessBuilder(
                        ytdlpPath,
                        "--newline",
                        "-f", formatCode,
                        "-o", downloadPath + File.separator + "%(title)s.%(ext)s",
                        url
                );
                if (maxVelocity > 0) {
                    pb.command().add("--limit-rate");
                    pb.command().add(maxVelocity + "K");
                }
                pb.redirectErrorStream(true);

                Process process = pb.start();
                BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
                String line;
                String lastLineWithQuotes = null;
                while ((line = reader.readLine()) != null) {
                    System.out.println(line);
                    Integer percent = parsePercentage(line);
                    if (percent != null) {
                        publish(percent);
                    }

                    if (line.contains("\"")) {
                        lastLineWithQuotes = line;
                    }
                }
                if (lastLineWithQuotes != null) {
                    int idx = lastLineWithQuotes.indexOf("\"");
                    int lastIdx = lastLineWithQuotes.lastIndexOf("\"");
                    if (idx >= 0 && lastIdx > idx) {
                        downloadedFilePath = lastLineWithQuotes.substring(idx + 1, lastIdx);
                    }
                }
                process.waitFor();
                publish(100); // asegurar 100% al final
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int last = chunks.get(chunks.size() - 1);
                jProgressBarDownload.setValue(last);
                jLabelProgress.setText(last + "%");
            }
            @Override
            protected void done() {
                if (downloadedFilePath != null && new File(downloadedFilePath).exists()) {
                    jButtonPlay.setVisible(true);
                } else {
                    System.out.println("Archivo final no encontrado: " + downloadedFilePath);
                }
            }
        };

        worker.execute();
    
    }//GEN-LAST:event_jButtonDownloadActionPerformed
    
    //Una vegada esta decarregat l'arxiu permet obrir i reproduir
    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        if (downloadedFilePath != null) {
            try {
                Desktop.getDesktop().open(new File(downloadedFilePath));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "No se pudo abrir el archivo: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonPlayActionPerformed
    
    //Carrega els formats disponibles de la URL
    private void loadFormats() {
        PreferencesPanel prefs = mainFrame.getPreferencesPanel();
        String url = jTextFieldURL.getText().trim();
        if (url.isEmpty()) return;
        // mostrar progress bar
        jProgressBarDownload.setIndeterminate(true);
        jProgressBarDownload.setVisible(true);
        jLabelLoadFormat.setVisible(true);
        SwingWorker<Void, String> worker = new SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                ProcessBuilder pb = new ProcessBuilder(
                    prefs.getYTDLPPath(), // ruta a yt-dlp
                    "-F",
                    url
                );
                pb.redirectErrorStream(true);
                Process process = pb.start();
                BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
                String line;
                while ((line = reader.readLine()) != null) {
                    // parsea solo líneas de formatos válidos
                    if (line.matches("\\d+.*")) {
                        publish(line); // envía al método process()
                    }
                }
                process.waitFor();
                return null;
            }

            @Override
            protected void process(java.util.List<String> chunks) {
                jComboBoxFormat.removeAllItems();
                for (String formatLine : chunks) {
                    // quitar el código inicial y dejar solo la descripción
                    String[] parts = formatLine.split("\\s+", 2); // separa en 2 partes: código y resto
                    if (parts.length > 1) {
                        jComboBoxFormat.addItem(parts[1]); // solo la descripción
                    } else {
                        jComboBoxFormat.addItem(parts[0]); // fallback si algo raro
                    }
                }
            }
            @Override
            protected void done() {
                jProgressBarDownload.setIndeterminate(false);
                jProgressBarDownload.setVisible(false);
                jLabelLoadFormat.setVisible(false);
            }
        };
        worker.execute();
    }
    
    //Despres d'aferrar la URL carrega els formats
    private void jTextFieldURLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldURLFocusLost
        loadFormats();
    }//GEN-LAST:event_jTextFieldURLFocusLost
    
    //Fa disponible el boto de descarregar una vegada s'ha seleccionat un format
    private void jComboBoxFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFormatActionPerformed
        if (jComboBoxFormat.getSelectedItem() != null) {
            jButtonDownload.setEnabled(true);
        } else {
            jButtonDownload.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxFormatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDownload;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JComboBox<String> jComboBoxFormat;
    private javax.swing.JLabel jLabelFormat;
    private javax.swing.JLabel jLabelLoadFormat;
    private javax.swing.JLabel jLabelProgress;
    private javax.swing.JLabel jLabelTittle;
    private javax.swing.JLabel jLabelURL;
    private javax.swing.JProgressBar jProgressBarDownload;
    private javax.swing.JTextField jTextFieldURL;
    // End of variables declaration//GEN-END:variables
}
