/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package anglada.sensebrutor;

/**
 *
 * @author Andreu
 */
public class PreferencesPanel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PreferencesPanel.class.getName());

    /**
     * Creates new form PreferencesPanel
     */
    public PreferencesPanel() {
        initComponents();
        setSize(800,600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPathTemporaryFiles = new javax.swing.JButton();
        jTextFieldPathTemporaryFiles = new javax.swing.JTextField();
        jLabelPathTemporaryFiles = new javax.swing.JLabel();
        jCheckBoxCreateM3U = new javax.swing.JCheckBox();
        jLabelVelocity = new javax.swing.JLabel();
        jSpinnerDownloadSpeed = new javax.swing.JSpinner();
        jLabelPathYTDLP = new javax.swing.JLabel();
        jTextFieldPathYTDLP = new javax.swing.JTextField();
        jButtonPathYTDLP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonPathTemporaryFiles.setText("Seleccionar Carpeta");
        getContentPane().add(jButtonPathTemporaryFiles);
        jButtonPathTemporaryFiles.setBounds(40, 60, 134, 23);

        jTextFieldPathTemporaryFiles.setEditable(false);
        jTextFieldPathTemporaryFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPathTemporaryFilesActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPathTemporaryFiles);
        jTextFieldPathTemporaryFiles.setBounds(180, 60, 260, 22);

        jLabelPathTemporaryFiles.setText("Ruta para archivos temporales");
        getContentPane().add(jLabelPathTemporaryFiles);
        jLabelPathTemporaryFiles.setBounds(40, 30, 160, 16);

        jCheckBoxCreateM3U.setText("Crear archivo .m3u");
        getContentPane().add(jCheckBoxCreateM3U);
        jCheckBoxCreateM3U.setBounds(40, 100, 150, 20);

        jLabelVelocity.setText("Velocidad máxima (KB/s)");
        getContentPane().add(jLabelVelocity);
        jLabelVelocity.setBounds(40, 140, 170, 16);
        getContentPane().add(jSpinnerDownloadSpeed);
        jSpinnerDownloadSpeed.setBounds(40, 170, 64, 22);

        jLabelPathYTDLP.setText("Ruta YT-DLP");
        getContentPane().add(jLabelPathYTDLP);
        jLabelPathYTDLP.setBounds(40, 210, 80, 16);

        jTextFieldPathYTDLP.setEditable(false);
        getContentPane().add(jTextFieldPathYTDLP);
        jTextFieldPathYTDLP.setBounds(190, 240, 240, 22);

        jButtonPathYTDLP.setText("Seleccionar archivo");
        getContentPane().add(jButtonPathYTDLP);
        jButtonPathYTDLP.setBounds(40, 240, 140, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPathTemporaryFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPathTemporaryFilesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPathTemporaryFilesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PreferencesPanel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPathTemporaryFiles;
    private javax.swing.JButton jButtonPathYTDLP;
    private javax.swing.JCheckBox jCheckBoxCreateM3U;
    private javax.swing.JLabel jLabelPathTemporaryFiles;
    private javax.swing.JLabel jLabelPathYTDLP;
    private javax.swing.JLabel jLabelVelocity;
    private javax.swing.JSpinner jSpinnerDownloadSpeed;
    private javax.swing.JTextField jTextFieldPathTemporaryFiles;
    private javax.swing.JTextField jTextFieldPathYTDLP;
    // End of variables declaration//GEN-END:variables
}
