
package anglada.sensebrutor;

import anglada.sensebrutor.model.ApiClient;
import anglada.sensebrutor.vista.MediaFilePanel;
import anglada.sensebrutor.vista.DownloadPanel;
import anglada.sensebrutor.vista.LoginPanel;
import anglada.sensebrutor.vista.PreferencesPanel;
import javax.swing.JMenuItem;


/**
 *
 * @author Andreu
 */
public final class SenseBrutor extends javax.swing.JFrame {
    public String jwt = "";
    private final DownloadPanel downloadpanel;
    private final PreferencesPanel preferencesPanel;
    private final MediaFilePanel mediaFilePanel;
    private final LoginPanel loginPanel;
    private final ApiClient apiClient = new ApiClient("https://dimedianetapi9.azurewebsites.net");
    /**
     * Creates new form SenseBrutor
     */
    
    public SenseBrutor() {
        initComponents();
        
        preferencesPanel = new PreferencesPanel(this);
        downloadpanel = new DownloadPanel(this);
        mediaFilePanel = new MediaFilePanel(this);
        loginPanel = new LoginPanel(this, apiClient);
        
        JMenuItem logoutItem = new JMenuItem("Cerrar sesión");
        logoutItem.addActionListener(e -> {
            loginPanel.limpiar();
            mostrarLogin();
        });
        jMenuFile.insert(logoutItem, 0);

        downloadpanel.setBounds(0, 0, 500, 340);
        mediaFilePanel.setBounds(500, 0, 550, 340);
        preferencesPanel.setBounds(0, 0, 500, 340);
        loginPanel.setBounds(0, 0, 1050, 340);

        getContentPane().add(downloadpanel);
        getContentPane().add(mediaFilePanel);
        getContentPane().add(preferencesPanel);
        getContentPane().add(loginPanel);
        setLayout(null);
        setSize(1050, 340);
        setLocationRelativeTo(null);
        setResizable(false);
        
        mostrarLogin();

    }
    public void mostrarLogin() {
        downloadpanel.setVisible(false);
        mediaFilePanel.setVisible(false);
        preferencesPanel.setVisible(false);
        loginPanel.setVisible(true);
        jMenuItemPreferences.setEnabled(false);
    }
    public void loginCorrecto() {
        loginPanel.setVisible(false);
        downloadpanel.setVisible(true);
        mediaFilePanel.setVisible(true);
        jMenuItemPreferences.setEnabled(true);
    }
    public void mostrarDownloadPanel() {
        preferencesPanel.setVisible(false);
        downloadpanel.setVisible(true);
    }
    public PreferencesPanel getPreferencesPanel() {
        return preferencesPanel;
    }
    public MediaFilePanel getMediaFilePanel() {
        return mediaFilePanel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAbout = new javax.swing.JDialog();
        jLabelNombre = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemPreferences = new javax.swing.JMenuItem();
        JMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        jDialogAbout.setTitle("Acerca de");
        jDialogAbout.setBounds(new java.awt.Rectangle(0, 0, 400, 325));
        jDialogAbout.getContentPane().setLayout(null);

        jLabelNombre.setText("<html>   <div style=\"text-align: center; font-family: Arial, sans-serif;\">     <img src=\"file:src/main/resources/images/logo.png\" width=\"100\" height=\"100\"><br><br>     <span style=\"font-size: 16pt; font-weight: bold;\">Andreu Anglada</span><br>     <span style=\"font-size: 12pt;\">Curso de Desarrollo de Interfaces - Grado Superior DAM</span><br><br>     <span style=\"font-size: 12pt; font-weight: bold;\">Recursos utilizados:</span><br>     <span style=\"font-size: 12pt;\">       YT-DLP, FFmpeg, Imágenes, NetBeans IDE 27, ChatGPT, YouTube canal SPDVI     </span><br><br>     <span style=\"font-size: 10pt; font-style: italic;\">       Gracias a todos los recursos mencionados por su disponibilidad.     </span>   </div> </html>");
        jDialogAbout.getContentPane().add(jLabelNombre);
        jLabelNombre.setBounds(70, 0, 250, 260);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(null);

        jMenuFile.setText("Archivo");

        jMenuItemExit.setText("Salir");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Editar");

        jMenuItemPreferences.setText("Configuración");
        jMenuItemPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPreferencesActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemPreferences);

        jMenuBar1.add(jMenuEdit);

        JMenuHelp.setText("Ayuda");

        jMenuItemAbout.setText("Acerca de...");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        JMenuHelp.add(jMenuItemAbout);

        jMenuBar1.add(JMenuHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPreferencesActionPerformed
        downloadpanel.setVisible(false);
        preferencesPanel.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemPreferencesActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed

        jDialogAbout.setModal(true);
        jDialogAbout.setLocationRelativeTo(this);
        jDialogAbout.setVisible(true);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SenseBrutor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuHelp;
    private javax.swing.JDialog jDialogAbout;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemPreferences;
    // End of variables declaration//GEN-END:variables
}
