
package anglada.sensebrutor;

/**
 *
 * @author Andreu
 */
public class SenseBrutor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SenseBrutor.class.getName());
    private DownloadPanel downloadpanel;
    private PreferencesPanel preferencesPanel;
    /**
     * Creates new form SenseBrutor
     */
    
    public SenseBrutor() {
        initComponents();
        setSize(550, 340);
        setLocationRelativeTo(null);

        downloadpanel = new DownloadPanel(this); 
        preferencesPanel = new PreferencesPanel(this); 
        downloadpanel.setBounds(0, 0, 550, 340);
        preferencesPanel.setBounds(0, 0, 550, 340);
        // Mostramos primero el panel principal
        getContentPane().add(downloadpanel);
        getContentPane().add(preferencesPanel);
        preferencesPanel.setVisible(false);
    }
    public void mostrarDownloadPanel() {
        preferencesPanel.setVisible(false);
        downloadpanel.setVisible(true);
    }
    public PreferencesPanel getPreferencesPanel() {
        return preferencesPanel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAbout = new javax.swing.JDialog();
        jLabelNombre = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemPreferences = new javax.swing.JMenuItem();
        JMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        jDialogAbout.setTitle("Acerca de");
        jDialogAbout.setBounds(new java.awt.Rectangle(0, 0, 400, 325));
        jDialogAbout.getContentPane().setLayout(null);

        jLabelNombre.setText("<html>   <div style=\"text-align: center; font-family: Arial, sans-serif;\">     <img src=\"file:src/main/resources/images/logo.png\" width=\"100\" height=\"100\"><br><br>     <span style=\"font-size: 16pt; font-weight: bold;\">Andreu Anglada</span><br>     <span style=\"font-size: 12pt;\">Curso de Desarrollo de Interfaces - Grado Superior DAM</span><br><br>     <span style=\"font-size: 12pt; font-weight: bold;\">Recursos utilizados:</span><br>     <span style=\"font-size: 12pt;\">       YT-DLP, FFmpeg, Imágenes, NetBeans IDE 27, ChatGPT, YouTube canal SPDVI     </span><br><br>     <span style=\"font-size: 10pt; font-style: italic;\">       Gracias a todos los recursos mencionados por su disponibilidad.     </span>   </div> </html>");
        jDialogAbout.getContentPane().add(jLabelNombre);
        jLabelNombre.setBounds(70, 0, 250, 260);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(null);

        jMenuFile.setText("Archivo");

        jMenuItemExit.setText("Salir");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Editar");

        jMenuItemPreferences.setText("Configuración");
        jMenuItemPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPreferencesActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemPreferences);

        jMenuBar1.add(jMenuEdit);

        JMenuHelp.setText("Ayuda");

        jMenuItemAbout.setText("Acerca de...");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        JMenuHelp.add(jMenuItemAbout);

        jMenuBar1.add(JMenuHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPreferencesActionPerformed
        downloadpanel.setVisible(false);
        preferencesPanel.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemPreferencesActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        // Configurar el dialogo si es necesario
        //jDialogAbout.setTitle("About");
        jDialogAbout.setModal(true);              // asegura que sea modal
        jDialogAbout.setLocationRelativeTo(this); // centra respecto al JFrame
        jDialogAbout.setVisible(true); 
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SenseBrutor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuHelp;
    private javax.swing.JDialog jDialogAbout;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemPreferences;
    // End of variables declaration//GEN-END:variables
}
