package anglada.sensebrutor.vista;

import anglada.sensebrutor.SenseBrutor;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Andreu
 */
public class DownloadPanel extends javax.swing.JPanel {

    /**
     * Creates new form DownloadPanel
     */
    private final SenseBrutor mainFrame;
    private String downloadedFilePath;
    public DownloadPanel(SenseBrutor mainFrame) {
        this.mainFrame = mainFrame;

        initComponents();
        jButtonPlay.setVisible(false);
        jButtonDownload.setEnabled(false);
        jProgressBarDownload.setVisible(false);
        jLabelLoadFormat.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTittle = new javax.swing.JLabel();
        jLabelURL = new javax.swing.JLabel();
        jTextFieldURL = new javax.swing.JTextField();
        jLabelFormat = new javax.swing.JLabel();
        jComboBoxFormat = new javax.swing.JComboBox<>();
        jButtonDownload = new javax.swing.JButton();
        jProgressBarDownload = new javax.swing.JProgressBar();
        jLabelProgress = new javax.swing.JLabel();
        jButtonPlay = new javax.swing.JButton();
        jLabelLoadFormat = new javax.swing.JLabel();

        setName("DownloadPanel"); // NOI18N
        setLayout(null);

        jLabelTittle.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabelTittle.setText("SenseBrutor");
        add(jLabelTittle);
        jLabelTittle.setBounds(200, 10, 170, 29);

        jLabelURL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelURL.setText("URL:");
        add(jLabelURL);
        jLabelURL.setBounds(70, 50, 30, 16);

        jTextFieldURL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldURLFocusLost(evt);
            }
        });
        add(jTextFieldURL);
        jTextFieldURL.setBounds(120, 48, 340, 30);

        jLabelFormat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelFormat.setText("Formato:");
        add(jLabelFormat);
        jLabelFormat.setBounds(60, 90, 60, 16);

        jComboBoxFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFormatActionPerformed(evt);
            }
        });
        add(jComboBoxFormat);
        jComboBoxFormat.setBounds(120, 90, 340, 30);

        jButtonDownload.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDownload.setText("Descargar");
        jButtonDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownloadActionPerformed(evt);
            }
        });
        add(jButtonDownload);
        jButtonDownload.setBounds(200, 130, 150, 23);
        add(jProgressBarDownload);
        jProgressBarDownload.setBounds(130, 180, 300, 30);
        add(jLabelProgress);
        jLabelProgress.setBounds(260, 160, 100, 16);

        jButtonPlay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPlay.setText("Reproducir");
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });
        add(jButtonPlay);
        jButtonPlay.setBounds(210, 220, 120, 23);

        jLabelLoadFormat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelLoadFormat.setText("Cargando formatos...");
        add(jLabelLoadFormat);
        jLabelLoadFormat.setBounds(230, 160, 140, 16);
    }// </editor-fold>//GEN-END:initComponents
    
    // Método simple per extreure el porcentge de descarrega la línea de yt-dlp per despres posar dins el progress bar
    /**
     * Font https://openai.com/es-ES/
     */
    private Integer parsePercentage(String line) {
        try {
            line = line.trim();
            if (line.startsWith("[download]") && line.contains("%")) {
                int idx = line.indexOf("%");
                String perc = line.substring(0, idx).replace("[download]", "").trim(); // "40.0"
                float f = Float.parseFloat(perc); 
                return Math.round(f); 
            }
        } catch (NumberFormatException e) {
            System.out.println("Error al sacar el % del progressbar");
        }
        return null;
    }
    
    /*Accio del boto descarregar, inclou progresbar i quan troba " " una vegada a finalitzat asigna la variable downloadedFilePath.
    downloadedFilePath serveix per una vegada descarregat obrir l'arxiu al reproductor predeterminat*/
    /**
     * Codi adaptat downloadVideo.java de Miguel Oscar García
     */
    private void iniciarDescarga(String ytdlpPath, String url, String formatCode, String downloadPath, int maxVelocity) {
        jProgressBarDownload.setVisible(true);
        jProgressBarDownload.setValue(0);
        jLabelProgress.setText("0%");

        SwingWorker<Void, Integer> worker = new SwingWorker<>() {
            boolean formatError = false;
            boolean yaExiste = false;
            @Override
            protected Void doInBackground() throws Exception {
                ProcessBuilder pb = new ProcessBuilder(
                        ytdlpPath,
                        "--newline",
                        "--restrict-filenames",
                        "-f", formatCode,
                        "-o", downloadPath + File.separator + "%(title)s.%(ext)s",
                        url
                );
                
                //Velocitat máxima
                if (maxVelocity > 0) {
                    pb.command().add("--limit-rate");
                    pb.command().add(maxVelocity + "K");
                }

                pb.redirectErrorStream(true);
                Process process = pb.start();
                BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
                String line;
                String lastLineWithQuotes = null;
                Boolean fixedUp = false;
                while ((line = reader.readLine()) != null) {
                    System.out.println(line);
                    Integer percent = parsePercentage(line);
                    if (percent != null) publish(percent);
                    
                    // Agregat per si surt error hora de descargar per format inexistent
                    if (line.contains("ERROR:")) {
                        formatError = true;
                    }
                    //Mostrar mensatge dient que s'arxiu ja existeix
                    if (line.contains("has already been downloaded")) {
                        yaExiste = true;
                    }
                    
                    // Guardar la última línea que te comilles
                    if (line.contains("\"")) {
                        lastLineWithQuotes = line;
                    }
                    
                    //En cas de seleccionar M3U guardam ruta
                    if (line.startsWith("[FixupM3u8]")){
                        int idx = line.indexOf("\"");
                        int lastIdx = line.lastIndexOf("\"");
                        if (idx >= 0 && lastIdx > idx) {
                            downloadedFilePath = line.substring(idx + 1, lastIdx);
                            fixedUp = true;
                        }
                    }
                }
                
                if (lastLineWithQuotes != null && fixedUp == false) {
                    int idx = lastLineWithQuotes.indexOf("\"");
                    int lastIdx = lastLineWithQuotes.lastIndexOf("\"");
                    if (idx >= 0 && lastIdx > idx) {
                        downloadedFilePath = lastLineWithQuotes.substring(idx + 1, lastIdx);
                    }
                }

                process.waitFor();
                publish(100); // asegurar 100%
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int last = chunks.get(chunks.size() - 1);
                jProgressBarDownload.setValue(last);
                jLabelProgress.setText(last + "%");
            }

            @Override
            protected void done() {
                if (formatError) {
                    JOptionPane.showMessageDialog(
                        DownloadPanel.this,
                        "El formato seleccionado no está disponible.",
                        "Formato no disponible",
                        JOptionPane.WARNING_MESSAGE
                    );
                    return;
                }
                if (yaExiste) {
                    JOptionPane.showMessageDialog(
                        DownloadPanel.this,
                        "El archivo ya existe.",
                        "El archivo ya existe.",
                        JOptionPane.WARNING_MESSAGE
                    );
                    return;
                }
                if (downloadedFilePath != null && new File(downloadedFilePath).exists()) {
                    jButtonPlay.setVisible(true);
                    mainFrame.getMediaFilePanel().reloadIfConfigured();
                
                    PreferencesPanel prefs = mainFrame.getPreferencesPanel();
                    if (prefs.isCreateM3U()) {
                        try {
                            File downloadedFile = new File(downloadedFilePath);
                            File folder = downloadedFile.getParentFile();
                            File m3uFile = new File(folder, "playlist.m3u");

                            // Añadir el archivo descargado a la lista (modo append = true)
                            try (FileWriter fw = new FileWriter(m3uFile, true)) {
                                fw.write(downloadedFile.getAbsolutePath() + "\n");
                            }

                            System.out.println("Archivo M3U actualizado: " + m3uFile.getAbsolutePath());
                        } catch (IOException ex) {
                            System.err.println("Error al crear archivo M3U: " + ex.getMessage());
                        }
                    }
                } else {
                    System.out.println("Archivo final no encontrado: " + downloadedFilePath);
                }
            }
        };

        worker.execute();
    }
    
    private void jButtonDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownloadActionPerformed
        PreferencesPanel prefs = mainFrame.getPreferencesPanel();

        String downloadPath = prefs.getDownloadPath();
        if (downloadPath.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "No se ha configurado una carpeta de destino.\nSelecciona una para guardar las descargas.",
                "Seleccionar carpeta de descarga",
                JOptionPane.INFORMATION_MESSAGE
            );
            prefs.elegirCarpetaDescarga();
            downloadPath = prefs.getDownloadPath();
            if (downloadPath.isEmpty()) return;
        }
        jLabelProgress.setVisible(true);
        String ytdlpPath = prefs.getYTDLPPath();
        String selectedItem = (String) jComboBoxFormat.getSelectedItem();
        String formatCode = "best";
        if (selectedItem != null && selectedItem.contains("|")) {
            formatCode = selectedItem.split("\\|")[0].trim();  // <- coge el número antes del '|'
        }
        int maxVelocity = prefs.getMaxVelocity();
        String url = jTextFieldURL.getText().trim();

        if (url.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, introduce una URL válida.");
            return;
        }

        iniciarDescarga(ytdlpPath, url, formatCode, downloadPath, maxVelocity);
    
    }//GEN-LAST:event_jButtonDownloadActionPerformed
    
    //Una vegada esta decarregat l'arxiu permet obrir i reproduir
    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        if (downloadedFilePath != null) {
            try {
                Desktop.getDesktop().open(new File(downloadedFilePath));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "No se pudo abrir el archivo: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonPlayActionPerformed
    
    //Carrega els formats disponibles de la URL
    /**
     * Codi d'ajuda generat per la font https://openai.com/es-ES/
     */
    private void loadFormats() {
        
        PreferencesPanel prefs = mainFrame.getPreferencesPanel();
        String ytdlpPath = prefs.getYTDLPPath();
        String url = jTextFieldURL.getText().trim();
        if (url.isEmpty())
            return;
        else {
            if (ytdlpPath == null || ytdlpPath.isEmpty()) {
                JOptionPane.showMessageDialog(
                    this,
                    "No se ha configurado la ruta del ejecutable de yt-dlp.\nPor favor, selecciona el archivo.",
                    "Ruta de yt-dlp requerida",
                    JOptionPane.INFORMATION_MESSAGE
                );
                prefs.elegirArchivoYTDLP();
            }
        }
        
        // mostrar progress bar
        jProgressBarDownload.setIndeterminate(true);
        jProgressBarDownload.setVisible(true);
        jLabelLoadFormat.setVisible(true);
        SwingWorker<Void, String> worker = new SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                ProcessBuilder pb = new ProcessBuilder(
                    prefs.getYTDLPPath(), 
                    "-F",
                    url
                );
                pb.redirectErrorStream(true);
                Process process = pb.start();
                BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
                String line;
                while ((line = reader.readLine()) != null) {
                    
                    if (line.trim().matches("^\\d+.*")) {
                        publish(line); 
                    }
                }
                process.waitFor();
                return null;
            }

            @Override
            protected void process(java.util.List<String> chunks) {
                jComboBoxFormat.removeAllItems();
                for (String formatLine : chunks) {
                    // LLevar el codi inicial i dexiar descripcio del format
                    String[] parts = formatLine.split("\\s+", 2); // separa en 2 parts: codi y resto
                    String code = parts[0];
                    String desc = (parts.length > 1) ? parts[1] : "";
                    jComboBoxFormat.addItem(code + " | " + desc);
                }
            }
            @Override
            protected void done() {
                jProgressBarDownload.setIndeterminate(false);
                jProgressBarDownload.setVisible(false);
                jLabelLoadFormat.setVisible(false);
            }
        };
        worker.execute();
    }
    
   
    //Fa disponible el boto de descarregar una vegada s'ha seleccionat un format
    private void jComboBoxFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFormatActionPerformed
        //Los pongo invisibles por si se vuelva a elegir otra url
        
        if (jComboBoxFormat.getSelectedItem() != null) {
            jButtonDownload.setEnabled(true);
        } else {
            jButtonDownload.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxFormatActionPerformed

    private void jTextFieldURLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldURLFocusLost
        jLabelProgress.setVisible(false);
        jButtonPlay.setVisible(false);
        loadFormats();
        
    }//GEN-LAST:event_jTextFieldURLFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDownload;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JComboBox<String> jComboBoxFormat;
    private javax.swing.JLabel jLabelFormat;
    private javax.swing.JLabel jLabelLoadFormat;
    private javax.swing.JLabel jLabelProgress;
    private javax.swing.JLabel jLabelTittle;
    private javax.swing.JLabel jLabelURL;
    private javax.swing.JProgressBar jProgressBarDownload;
    private javax.swing.JTextField jTextFieldURL;
    // End of variables declaration//GEN-END:variables
}
