package anglada.sensebrutor.vista;

import anglada.sensebrutor.SenseBrutor;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

/**
 *
 * @author Andreu
 */
public class DownloadPanel extends javax.swing.JPanel {

    /**
     * Creates new form DownloadPanel
     */
    private final SenseBrutor mainFrame;
    private String downloadedFilePath;
    public DownloadPanel(SenseBrutor mainFrame) {
        this.mainFrame = mainFrame;

        initComponents();
        jButtonPlay.setVisible(false);
        jButtonDownload.setEnabled(false);
        jProgressBarDownload.setVisible(false);
        jLabelLoadFormat.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTittle = new javax.swing.JLabel();
        jLabelURL = new javax.swing.JLabel();
        jTextFieldURL = new javax.swing.JTextField();
        jLabelFormat = new javax.swing.JLabel();
        jComboBoxFormat = new javax.swing.JComboBox<>();
        jButtonDownload = new javax.swing.JButton();
        jProgressBarDownload = new javax.swing.JProgressBar();
        jLabelProgress = new javax.swing.JLabel();
        jButtonPlay = new javax.swing.JButton();
        jLabelLoadFormat = new javax.swing.JLabel();

        setName("DownloadPanel"); // NOI18N
        setLayout(null);

        jLabelTittle.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabelTittle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/titulosensebruto1r.png"))); // NOI18N
        jLabelTittle.setToolTipText("");
        add(jLabelTittle);
        jLabelTittle.setBounds(110, 0, 320, 120);

        jLabelURL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelURL.setText("URL:");
        add(jLabelURL);
        jLabelURL.setBounds(80, 120, 30, 16);

        jTextFieldURL.setToolTipText("Video de youtube a descargar.");
        jTextFieldURL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldURLFocusLost(evt);
            }
        });
        add(jTextFieldURL);
        jTextFieldURL.setBounds(120, 110, 340, 30);

        jLabelFormat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelFormat.setText("Formato:");
        add(jLabelFormat);
        jLabelFormat.setBounds(60, 160, 60, 16);

        jComboBoxFormat.setToolTipText("Formato de salida.");
        jComboBoxFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFormatActionPerformed(evt);
            }
        });
        add(jComboBoxFormat);
        jComboBoxFormat.setBounds(120, 150, 340, 30);

        jButtonDownload.setBackground(new java.awt.Color(78, 78, 255));
        jButtonDownload.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDownload.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconoyoutube1.png"))); // NOI18N
        jButtonDownload.setText("Descargar");
        jButtonDownload.setToolTipText("Acción que descarga el video del formato seleccionado y lo guarda en a la carpeta asignada en configuración.");
        jButtonDownload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownloadActionPerformed(evt);
            }
        });
        add(jButtonDownload);
        jButtonDownload.setBounds(190, 190, 190, 50);
        add(jProgressBarDownload);
        jProgressBarDownload.setBounds(130, 270, 300, 30);
        add(jLabelProgress);
        jLabelProgress.setBounds(260, 250, 90, 16);

        jButtonPlay.setBackground(new java.awt.Color(204, 255, 204));
        jButtonPlay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playyoutbebrili.png"))); // NOI18N
        jButtonPlay.setText("Reproducir");
        jButtonPlay.setToolTipText("Reproducir con reproductor predeterminado.");
        jButtonPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });
        add(jButtonPlay);
        jButtonPlay.setBounds(190, 310, 180, 39);

        jLabelLoadFormat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelLoadFormat.setText("Cargando formatos...");
        add(jLabelLoadFormat);
        jLabelLoadFormat.setBounds(240, 250, 140, 16);
    }// </editor-fold>//GEN-END:initComponents
    
    // Método simple per extreure el porcentge de descarrega la línea de yt-dlp per despres posar dins el progress bar
    /**
     * Font https://openai.com/es-ES/
     */
    private Integer parsePercentage(String line) {
        try {
            line = line.trim();
            if (line.startsWith("[download]") && line.contains("%")) {
                int idx = line.indexOf("%");
                String perc = line.substring(0, idx).replace("[download]", "").trim(); // "40.0"
                float f = Float.parseFloat(perc); 
                return Math.round(f); 
            }
        } catch (NumberFormatException e) {
            System.out.println("Error al sacar el % del progressbar");
        }
        return null;
    }
    /**
    * Inicia la descàrrega només d'àudio i el converteix a MP3
    */
   private void iniciarDescargaAudio(String ytdlpPath, String url, String downloadPath, int maxVelocity) {
       jProgressBarDownload.setVisible(true);
       jProgressBarDownload.setValue(0);
       jLabelProgress.setText("0%");

       SwingWorker<Void, Integer> worker = new SwingWorker<>() {
           boolean yaExiste = false;
           String downloadedFilePathTemp = null;

           @Override
           protected Void doInBackground() throws Exception {
               ProcessBuilder pb = new ProcessBuilder(
                   ytdlpPath,
                   "-x",                           // extreure només àudio
                   "--audio-format", "mp3",        // convertir a mp3
                   "--audio-quality", "0",      // es pot posar 192 kbps
                   "--embed-thumbnail",
                   "--add-metadata",
                   "--restrict-filenames",
                   "-o", downloadPath + File.separator + "%(title)s.%(ext)s",
                   url
               );

               if (maxVelocity > 0) {
                   pb.command().add("--limit-rate");
                   pb.command().add(maxVelocity + "K");
               }

               pb.redirectErrorStream(true);
               Process process = pb.start();
               BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));

               String line;
               String lastLineWithQuotes = null;

               while ((line = reader.readLine()) != null) {
                   System.out.println(line);

                   Integer percent = parsePercentage(line);
                   if (percent != null) {
                       publish(percent);
                   }

                   if (line.contains("has already been downloaded")) {
                       yaExiste = true;
                   }

                   if (line.contains("\"")) {
                       lastLineWithQuotes = line;
                   }

                   // Per mp3 normalment no hi ha [FixupM3u8], però per si de cas
                   if (line.startsWith("[ExtractAudio]") || line.startsWith("[Merger]") || line.startsWith("[download]")) {
                       // Podem intentar capturar el nom del fitxer aquí
                       int idx = line.indexOf("\"");
                       int lastIdx = line.lastIndexOf("\"");
                       if (idx >= 0 && lastIdx > idx) {
                           downloadedFilePathTemp = line.substring(idx + 1, lastIdx);
                       }
                   }
               }

               // Últim intent per capturar el nom del fitxer si no s'ha trobat abans
               if (lastLineWithQuotes != null && downloadedFilePathTemp == null) {
                   int idx = lastLineWithQuotes.indexOf("\"");
                   int lastIdx = lastLineWithQuotes.lastIndexOf("\"");
                   if (idx >= 0 && lastIdx > idx) {
                       downloadedFilePathTemp = lastLineWithQuotes.substring(idx + 1, lastIdx);
                   }
               }

               process.waitFor();
               publish(100);

               return null;
           }

           @Override
           protected void process(java.util.List<Integer> chunks) {
               int last = chunks.get(chunks.size() - 1);
               jProgressBarDownload.setValue(last);
               jLabelProgress.setText(last + "%");
           }

           @Override
           protected void done() {
               if (yaExiste) {
                   JOptionPane.showMessageDialog(
                       DownloadPanel.this,
                       "L'arxiu àudio ja existeix.",
                       "Fitxer existent",
                       JOptionPane.WARNING_MESSAGE
                   );
                   return;
               }

               if (downloadedFilePathTemp != null && new File(downloadedFilePathTemp).exists()) {
                   downloadedFilePath = downloadedFilePathTemp;
                   jButtonPlay.setVisible(true);
                   mainFrame.getMediaFilePanel().reloadIfConfigured();

                   // Opcional: actualitzar playlist.m3u si està activat
                   if (mainFrame.getPreferencesPanel().isCreateM3U()) {
                       try {
                           File downloadedFile = new File(downloadedFilePath);
                           File folder = downloadedFile.getParentFile();
                           File m3uFile = new File(folder, "playlist.m3u");

                           try (FileWriter fw = new FileWriter(m3uFile, true)) {
                               fw.write(downloadedFile.getAbsolutePath() + "\n");
                           }
                           System.out.println("Playlist M3U actualitzada: " + m3uFile.getAbsolutePath());
                       } catch (IOException ex) {
                           System.err.println("Error al crear/actualitzar M3U: " + ex.getMessage());
                       }
                   }
               } else {
                   JOptionPane.showMessageDialog(
                       DownloadPanel.this,
                       "No se ha podido encontrar el archivo descargado.",
                       "Error en la descarrega",
                       JOptionPane.ERROR_MESSAGE
                   );
                   System.out.println("No se ha podido encontrar el archivo descargado: " + downloadedFilePathTemp);
               }
           }
       };

       worker.execute();
   }
    /**
    * Acció del botó descarregar: inclou barra de progrés i assigna downloadedFilePath
    * un cop finalitzat, per poder reproduir el fitxer descarregat.
    */
    private void iniciarDescarga(String ytdlpPath, String url, String formatCode, String downloadPath, int maxVelocity) {
        jProgressBarDownload.setVisible(true);
        jProgressBarDownload.setValue(0);
        jLabelProgress.setText("Descargando...");

        SwingWorker<Void, String> worker = new SwingWorker<>() {
            String lastSavedFile = null;
            boolean yaExiste = false;

            @Override
            protected Void doInBackground() throws Exception {
                ProcessBuilder pb = new ProcessBuilder();

                pb.command().add(ytdlpPath);
                pb.command().add("--newline");
                pb.command().add("--restrict-filenames");
                pb.command().add("--no-playlist");
                pb.command().add("--retries"); pb.command().add("3");
                pb.command().add("--fragment-retries"); pb.command().add("3");

                // Forcem format correcte
                if (formatCode != null) {
                    if (formatCode.toLowerCase().contains("mp4")) {
                        pb.command().add("-f");
                        pb.command().add("bv*[ext=mp4]+ba[ext=m4a]/best[ext=mp4]/best");
                    } else if (formatCode.toLowerCase().contains("mp3")) {
                        pb.command().add("-x");
                        pb.command().add("--audio-format");
                        pb.command().add("mp3");
                    } else {
                        pb.command().add("-f");
                        pb.command().add(formatCode);
                    }
                }

                if (maxVelocity > 0) {
                    pb.command().add("--limit-rate");
                    pb.command().add(maxVelocity + "K");
                }

                pb.command().add("-o");
                pb.command().add(downloadPath + File.separator + "%(title)s.%(ext)s");
                pb.command().add(url);

                pb.redirectErrorStream(true);
                Process process = pb.start();

                BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream(), StandardCharsets.UTF_8));
                String line;

                while ((line = reader.readLine()) != null) {
                    publish(line);

                    // Detectem "already been downloaded" com abans
                    if (line.contains("has already been downloaded")) {
                        yaExiste = true;
                    }

                    // Parseig del nom final
                    if (line.contains("Moving file") && line.contains("\" to \"")) {
                        String[] parts = line.split("\" to \"");
                        if (parts.length > 1) {
                            lastSavedFile = parts[1].substring(0, parts[1].length() - 1);
                        }
                    } else if (line.contains("Merging formats into")) {
                        String stringToRemove = "[Merger] Merging formats into";
                        lastSavedFile = line.substring(line.indexOf(stringToRemove) + stringToRemove.length()).trim();
                        lastSavedFile = lastSavedFile.replace("\"", "");
                    } else if (line.contains("[download] Destination:")) {
                        lastSavedFile = line.substring(line.indexOf(":") + 2).trim();
                    }
                }

                process.waitFor();

                return null;
            }

            @Override
            protected void process(List<String> chunks) {
                for (String line : chunks) {
                    if (line.contains("%")) {
                        Integer percent = parsePercentage(line);
                        if (percent != null) {
                            jProgressBarDownload.setValue(percent);
                            jLabelProgress.setText(percent + "%");
                        }
                    }
                }
            }

            @Override
            protected void done() {
                jProgressBarDownload.setVisible(false);
                jLabelProgress.setText("Finalizado");

                // Si ja existia, mostrem missatge i no error
                if (yaExiste) {
                    JOptionPane.showMessageDialog(DownloadPanel.this,
                        "El archivo ya existe en la carpeta.",
                        "Ya descargado",
                        JOptionPane.INFORMATION_MESSAGE);
                    return;
                }

                // Si hem capturat el nom i existeix → èxit
                if (lastSavedFile != null && new File(lastSavedFile).exists()) {
                    downloadedFilePath = lastSavedFile;
                    jButtonPlay.setVisible(true);
                    mainFrame.getMediaFilePanel().reloadIfConfigured();

                    if (mainFrame.getPreferencesPanel().isCreateM3U()) {
                        try {
                            File f = new File(downloadedFilePath);
                            File m3u = new File(f.getParentFile(), "playlist.m3u");
                            try (FileWriter fw = new FileWriter(m3u, true)) {
                                fw.write(f.getAbsolutePath() + "\n");
                            }
                        } catch (IOException ignored) {}
                    }
                } else {
                    JOptionPane.showMessageDialog(DownloadPanel.this,
                        "No se ha podido descargar.\nPrueba en otro momento.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        };

        worker.execute();
    }
    
    private void jButtonDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownloadActionPerformed
        jButtonPlay.setVisible(false);
        PreferencesPanel prefs = mainFrame.getPreferencesPanel();
        String downloadPath = prefs.getDownloadPath();
        if (downloadPath.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "No se ha configurado la carpeta de descargas.\nSelecciona una.", "Carpeta de destino",
                JOptionPane.INFORMATION_MESSAGE
            );
            prefs.elegirCarpetaDescarga();
            downloadPath = prefs.getDownloadPath();
            if (downloadPath.isEmpty()) return;
        }
        jLabelProgress.setVisible(true);
        String ytdlpPath = prefs.getYTDLPPath();
        String selectedItem = (String) jComboBoxFormat.getSelectedItem();
        if (selectedItem == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un formato primero.");
            return;
        }
        String url = jTextFieldURL.getText().trim();
        if (url.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduce una URL válida.");
            return;
        }
        int maxVelocity = prefs.getMaxVelocity();
        String formatCode;
        boolean isAudioMp3 = selectedItem.toLowerCase().contains("mp3");  // ← AQUEST ÉS EL CANVI CLAU
        if (isAudioMp3) {
            iniciarDescargaAudio(ytdlpPath, url, downloadPath, maxVelocity);
        } else {
            // ── Lògica per vídeo ───────────────────────────────
            if (selectedItem.startsWith("MEJOR |")) {
                formatCode = "best";
            } else if (selectedItem.startsWith("MP4 |")) {
                formatCode = "mp4";  // o el selector que vulguis
            } else {
                formatCode = selectedItem.split("\\|")[0].trim();
            }
            iniciarDescarga(ytdlpPath, url, formatCode, downloadPath, maxVelocity);
        }
    
    }//GEN-LAST:event_jButtonDownloadActionPerformed
    
    //Una vegada esta decarregat l'arxiu permet obrir i reproduir
    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        if (downloadedFilePath != null) {
            try {
                Desktop.getDesktop().open(new File(downloadedFilePath));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "No se pudo abrir el archivo: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonPlayActionPerformed
    
    //Carrega els formats disponibles de la URL
    /**
     * Codi d'ajuda generat per la font https://openai.com/es-ES/
     */
    /**
    * Carrega formats disponibles de la URL, però només mostra opcions útils i clares per l'usuari
    */
    private void loadFormats() {
        PreferencesPanel prefs = mainFrame.getPreferencesPanel();
        String ytdlpPath = prefs.getYTDLPPath();
        String url = jTextFieldURL.getText().trim();

        if (url.isEmpty()) {
            return;
        }

        if (ytdlpPath == null || ytdlpPath.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "No se ha configurado la ruta de yt-dlp.\nPor favor, selecciona el ejecutable.", "Ruta de yt-dlp necesaria",
                JOptionPane.INFORMATION_MESSAGE
            );
            prefs.elegirArchivoYTDLP();
            return;
        }

        // Mostrem indicadors de càrrega (encara que sigui ràpid)
        jProgressBarDownload.setIndeterminate(true);
        jProgressBarDownload.setVisible(true);
        jLabelLoadFormat.setVisible(true);
        jLabelLoadFormat.setText("Preparando opciones...");

        SwingWorker<Void, Void> worker = new SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                // No fem cap crida a yt-dlp -F → només preparem les opcions fixes
                // (podem afegir un petit delay si vols que es vegi la càrrega, però no cal)
                Thread.sleep(300); // opcional: perquè l'usuari vegi l'animació ~0.3 segons
                return null;
            }

            @Override
            protected void process(java.util.List<Void> chunks) {
                // No fem servir chunks aquí
            }

            @Override
            protected void done() {
                jComboBoxFormat.removeAllItems();

                // Només les 3 opcions que vols
                jComboBoxFormat.addItem("MEJOR | Mejor calidad disponible");
                jComboBoxFormat.addItem("MP4 | Vídeo en formato MP4");
                jComboBoxFormat.addItem("MP3 | Audio en formato MP3");

                // Seleccionem la primera per defecte
                jComboBoxFormat.setSelectedIndex(0);

                // Amaguem la càrrega
                jProgressBarDownload.setIndeterminate(false);
                jProgressBarDownload.setVisible(false);
                jLabelLoadFormat.setVisible(false);

                // Activem el botó de descàrrega
                jButtonDownload.setEnabled(true);
            }
        };

        worker.execute();
    }
    
   
    //Fa disponible el boto de descarregar una vegada s'ha seleccionat un format
    private void jComboBoxFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFormatActionPerformed
        //Los pongo invisibles por si se vuelva a elegir otra url
        
        if (jComboBoxFormat.getSelectedItem() != null) {
            jButtonDownload.setEnabled(true);
        } else {
            jButtonDownload.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxFormatActionPerformed

    private void jTextFieldURLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldURLFocusLost
        jLabelProgress.setVisible(false);
        jButtonPlay.setVisible(false);
        loadFormats();
        
    }//GEN-LAST:event_jTextFieldURLFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDownload;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JComboBox<String> jComboBoxFormat;
    private javax.swing.JLabel jLabelFormat;
    private javax.swing.JLabel jLabelLoadFormat;
    private javax.swing.JLabel jLabelProgress;
    private javax.swing.JLabel jLabelTittle;
    private javax.swing.JLabel jLabelURL;
    private javax.swing.JProgressBar jProgressBarDownload;
    private javax.swing.JTextField jTextFieldURL;
    // End of variables declaration//GEN-END:variables
}
