package anglada.sensebrutor.vista;

import anglada.sensebrutor.SenseBrutor;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Andreu
 */
public class PreferencesPanel extends javax.swing.JPanel {

    /**
     * Creates new form PreferencesPanel
     */
    private final SenseBrutor mainFrame;
    public PreferencesPanel(SenseBrutor mainFrame) {
        initComponents();
        this.mainFrame = mainFrame; 
    }
    
    /*Serie de funcions necessaries per la descarrega*/
    public String getDownloadPath() {
        return jTextFieldDownloadPath.getText().trim();
    }

    public String getYTDLPPath() {
        return jTextFieldPathYTDLP.getText().trim();
    }

    public int getMaxVelocity() {
        return (Integer) jSpinnerVelocity.getValue();
    }

    public boolean isCreateM3U() {
        return jCheckBoxM3u.isSelected();
    }
    
    //Funcio necessaria a l'hora d'apretar descargar sense tenir definit ruta sortida
    public void elegirCarpetaDescarga() {
        jButtonDownloadPathActionPerformed(null);
    }
    
    //Funcio necessaria a l'hora d'agregar formats
    public void elegirArchivoYTDLP() {
        jButtonPathYTDLPActionPerformed(null);
    }
    /**
    * Reinicia tots els camps del PreferencesPanel a valors per defecte.
    */
   public void reiniciar() {
       jTextFieldDownloadPath.setText("");
       jTextFieldPathYTDLP.setText("");
       jSpinnerVelocity.setValue(0);
       jCheckBoxM3u.setSelected(false);
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserGeneral = new javax.swing.JFileChooser();
        jLabelDownloadPathFile = new javax.swing.JLabel();
        jButtonDownloadPath = new javax.swing.JButton();
        jTextFieldDownloadPath = new javax.swing.JTextField();
        jCheckBoxM3u = new javax.swing.JCheckBox();
        jLabelVelocity = new javax.swing.JLabel();
        jSpinnerVelocity = new javax.swing.JSpinner();
        jLabelPathYTDLP = new javax.swing.JLabel();
        jButtonPathYTDLP = new javax.swing.JButton();
        jTextFieldPathYTDLP = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jFileChooserGeneral.setApproveButtonText("Seleccionar");
        jFileChooserGeneral.setDialogTitle("Selecciona una carpeta para guardar");
        jFileChooserGeneral.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setName("PreferencesPanel"); // NOI18N
        setLayout(null);

        jLabelDownloadPathFile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDownloadPathFile.setText("Guardar archivo en");
        add(jLabelDownloadPathFile);
        jLabelDownloadPathFile.setBounds(50, 10, 190, 16);

        jButtonDownloadPath.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDownloadPath.setText("Seleccionar Carpeta");
        jButtonDownloadPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownloadPathActionPerformed(evt);
            }
        });
        add(jButtonDownloadPath);
        jButtonDownloadPath.setBounds(50, 30, 160, 23);
        add(jTextFieldDownloadPath);
        jTextFieldDownloadPath.setBounds(220, 30, 281, 22);

        jCheckBoxM3u.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxM3u.setText("Crear archivo .m3u");
        add(jCheckBoxM3u);
        jCheckBoxM3u.setBounds(50, 70, 170, 20);

        jLabelVelocity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelVelocity.setText("Velocidad máxima (KB/s)");
        add(jLabelVelocity);
        jLabelVelocity.setBounds(50, 110, 150, 16);
        add(jSpinnerVelocity);
        jSpinnerVelocity.setBounds(220, 110, 64, 22);

        jLabelPathYTDLP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPathYTDLP.setText("Ruta YT-DLP");
        add(jLabelPathYTDLP);
        jLabelPathYTDLP.setBounds(50, 150, 130, 16);

        jButtonPathYTDLP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPathYTDLP.setText("Seleccionar archivo");
        jButtonPathYTDLP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPathYTDLPActionPerformed(evt);
            }
        });
        add(jButtonPathYTDLP);
        jButtonPathYTDLP.setBounds(50, 180, 160, 23);
        add(jTextFieldPathYTDLP);
        jTextFieldPathYTDLP.setBounds(220, 180, 290, 22);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("!DESCARGAR YA!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(160, 230, 260, 23);
    }// </editor-fold>//GEN-END:initComponents
    
    //FileChooser que permet navegar i seleccionar una ruta directori
    private void jButtonDownloadPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownloadPathActionPerformed
        jFileChooserGeneral.setDialogTitle("Selecciona la carpeta donde guardar");
        jFileChooserGeneral.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = jFileChooserGeneral.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File carpeta = jFileChooserGeneral.getSelectedFile();
            String ruta = carpeta.getAbsolutePath();
            // Guarda la ruta en una variable o textfield
            jTextFieldDownloadPath.setText(ruta);
            if (mainFrame != null && mainFrame.getMediaFilePanel() != null) {
                mainFrame.getMediaFilePanel().reloadIfConfigured();
            }
        }
    }//GEN-LAST:event_jButtonDownloadPathActionPerformed
    
    //FileChooser que permet navegar i seleccionar una ruta arxiu
    private void jButtonPathYTDLPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPathYTDLPActionPerformed
        jFileChooserGeneral.setDialogTitle("Selecciona el archivo de yt-dlp");
        jFileChooserGeneral.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int result = jFileChooserGeneral.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File archivo = jFileChooserGeneral.getSelectedFile();
            jTextFieldPathYTDLP.setText(archivo.getAbsolutePath());
        }
    }//GEN-LAST:event_jButtonPathYTDLPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainFrame.mostrarDownloadPanel();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDownloadPath;
    private javax.swing.JButton jButtonPathYTDLP;
    private javax.swing.JCheckBox jCheckBoxM3u;
    private javax.swing.JFileChooser jFileChooserGeneral;
    private javax.swing.JLabel jLabelDownloadPathFile;
    private javax.swing.JLabel jLabelPathYTDLP;
    private javax.swing.JLabel jLabelVelocity;
    private javax.swing.JSpinner jSpinnerVelocity;
    private javax.swing.JTextField jTextFieldDownloadPath;
    private javax.swing.JTextField jTextFieldPathYTDLP;
    // End of variables declaration//GEN-END:variables
}
